---
data:
  data_root: database/church_outdoor_sdedit
  image_size: 256
  num_workers: 4
  rescaled: true
model:
  attn_resolutions:
    - 16
  ch: 128
  ch_mult:
    - 1
    - 1
    - 2
    - 2
    - 4
    - 4
  dropout: 0
  ema: true
  ema_rate: 0.999
  in_ch: 3
  network: ddpm.unet
  num_res_blocks: 2
  out_ch: 3
  resamp_with_conv: true
  sige_block_size:
    instance: 4
    normal: 6
  var_type: fixedsmall
sampling:
  algorithm_type: dpmsolver++
  beta_end: 0.02
  beta_schedule: linear
  beta_start: 1.0E-4
  eps: 0.01
  lower_order_final: true
  mask_dilate_radius: 5
  noise_level: 750
  order: 2
  sample_steps: 10
  sampler_type: dpm_solver
  skip_type: uniform
  solver_type: dpmsolver
  total_steps: 1000
